### ISSUE TITLE
Request Zen port

### ISSUE THREAD

**Issue by Scottrock** [vaklinov/zclassic-swing-wallet-ui#2]
Are you contemplating a Zen wallet (zend and zen-cli compatible replacing zcashd and zcash-cli)?

**Comment by vaklinov** [comment]
Making a Zen wallet is an option but it will depend on whether the Zen community truly needs it. The ZClassic developers are currently favouring an alternative GUI wallet (Eleos). In addition I have received no (meaningful) donations from ZClassic users so far ... so my own incentive to develop the ZClassic/Zen line of wallets is a bit diminished.

**Comment by Scottrock** [comment]
In case you are interested.
https://github.com/Scottrock/zen-swing-wallet-ui
Sorry - I am new to Git, so I didn't know how to fork properly.
If this offends - I will take it down.
regards
Scottrock

**Comment by vaklinov** [comment]
I am certainly *not* offended. Everyone is free to fork and change the source to benefit different crypto-communities. Feel free to advertise your ZEN wallet e.g. on the forum:
https://bitcointalk.org/index.php?topic=1819977.1220
since I am not planning to do a ZEN wallet myself .. for now.

**Comment by vaklinov** [comment]
ZEN Port is now available:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui
